# @package _global_

## Config for the Janner Diffuser model specifically on the MuJoCo environment

dataset:
  normalizers:
    mc_returns:
      value: 4
  max_episode_length: 280
  terminal_penalty: 0.
  discount: 0.997 # Repo uses 0.99, clean diffuser uses 0.997

renderer:
  _target_: tgdp.rendering.MuJoCoKitchenRenderer
  env_name: ${env}
  # Render Kwargs
  trackbodyid: 2
  distance: 10
  lookat: [5, 2, 0.5]
  elevation: 0
