# @package _global_

# diffusion
diffusion_model:
  guide_scale: 3.2

# dataset
dataset:
  normalizers:
    mc_returns:
      value: 1700.

# guides
guides:
  trajectory_return:
    cfg_target_value: 1.1
