# @package _global_

# diffusion
diffusion_model:
  guide_scale: 2.4

# dataset
dataset:
  normalizers:
    mc_returns:
      value: 1300.

# guides
guides:
  trajectory_return:
    cfg_target_value: 0.75
